name: 0FA CTF
logo: "/assets/images/0fa.png"

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "neon"

paginate: 4
paginate_path: /page:num/

defaults:
    - scope:
        path: ""
        type: posts
      values:
        layout: single
        toc: true
        toc_sticky: true
        read_time: true
        related: true

url: "/"
baseurl: "/"

# Don't touch below, unless you know what you're doing

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
